# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170909_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_registered',
            new_name='date_joined',
        ),
    ]
