# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='graduates',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
