# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_batch_graduates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='graduates',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
